version: "2.1"



services:
  task-tracker:
    image: task-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - task-tracker-network
    
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_tracker
    ports:
      - "5432:5432"
    networks:
      - task-tracker-network
      - postgres-network
  
  diary-api:
    image: diary-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
    networks:
      - task-tracker-network